#!/bin/bash
CONFIG="/etc/xray/config.json"
LOG_FILE="/var/log/xp-zivpn.log"
YEAR=$(date +%Y)
if [ "$YEAR" -lt "2025" ]; then
    echo "$(date): [ABORT] Waktu sistem tidak valid (Year: $YEAR). Script dihentikan demi keamanan." >> $LOG_FILE
    exit 1
fi
# Backup config sebelum dieksekusi, jaga-jaga jika corrupt
cp $CONFIG /etc/xray/config.json.bak
echo "--- Start Checking: $(date) ---" >> $LOG_FILE
function delete_xray_user() {
    local user=$1
    local exp=$2
    local tag=$3
    user_safe=$(echo "$user" | sed 's/\//\\\//g')
    sed -i "/^$tag $user_safe $exp/,/^},{/d" $CONFIG
    rm -f /etc/xray/$user-tls.json
    rm -f /etc/vless/$user
    rm -f /etc/trojan/$user
    rm -f /etc/kyt/limit/vless/ip/$user
    rm -f /etc/kyt/limit/trojan/ip/$user
    rm -f /etc/kyt/limit/shadowsocks/ip/$user
    
    echo "Deleted Xray User: $user ($tag)" >> $LOG_FILE
}
now=$(date +%Y-%m-%d)
now_sec=$(date +%s)
grep "^###" $CONFIG | while read -r line; do
    user=$(echo $line | cut -d ' ' -f 2)
    exp=$(echo $line | cut -d ' ' -f 3)   
    exp_sec=$(date -d "$exp" +%s 2>/dev/null)
    if [[ -z "$exp_sec" ]]; then continue; fi
    if [[ $exp_sec -le $now_sec ]]; then
        delete_xray_user "$user" "$exp" "###"
    fi
done
grep "^#&" $CONFIG | while read -r line; do
    user=$(echo $line | cut -d ' ' -f 2)
    exp=$(echo $line | cut -d ' ' -f 3)
    exp_sec=$(date -d "$exp" +%s 2>/dev/null)
    if [[ -z "$exp_sec" ]]; then continue; fi
    
    if [[ $exp_sec -le $now_sec ]]; then
        delete_xray_user "$user" "$exp" "#&"
    fi
done
grep "^#!" $CONFIG | while read -r line; do
    user=$(echo $line | cut -d ' ' -f 2)
    exp=$(echo $line | cut -d ' ' -f 3)
    exp_sec=$(date -d "$exp" +%s 2>/dev/null)
    if [[ -z "$exp_sec" ]]; then continue; fi

    if [[ $exp_sec -le $now_sec ]]; then
        delete_xray_user "$user" "$exp" "#!"
    fi
done
grep "^#ss#" $CONFIG | while read -r line; do
    user=$(echo $line | cut -d ' ' -f 2)
    exp=$(echo $line | cut -d ' ' -f 3)
    exp_sec=$(date -d "$exp" +%s 2>/dev/null)
    if [[ -z "$exp_sec" ]]; then continue; fi

    if [[ $exp_sec -le $now_sec ]]; then
        delete_xray_user "$user" "$exp" "#ss#"
        # Hapus juga dari database manual SS jika ada
        sed -i "/^### $user /d" /etc/shadowsocks/.shadowsocks.db
    fi
done
sed -i 's/,\s*]/]/g' $CONFIG
sed -i 's/,\s*}/}/g' $CONFIG
if ! jq . $CONFIG > /dev/null 2>&1; then
    echo "$(date): [CRITICAL] JSON Corrupt detected after XP! Restoring backup..." >> $LOG_FILE
    cp /etc/xray/config.json.bak $CONFIG
    systemctl restart xray
    exit 1
fi
systemctl restart xray
cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
while IFS=: read -r username userexp; do
    if [[ -z "$userexp" ]]; then continue; fi
    userexp_sec=$((userexp * 86400))    
    if [[ $userexp_sec -lt $now_sec ]]; then
        if id "$username" &>/dev/null; then
             userdel --force "$username"
             echo "Deleted SSH User: $username" >> $LOG_FILE
        fi
    fi
done < /tmp/expirelist.txt

rm -f /tmp/expirelist.txt